[package]
name = "meshanina"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "2.1.0"
ethnum = "1.0.4"
zeroize = "1.4.3"
parking_lot = "0.11.1"
cache-padded = "1.1.1"
memmap = "0.7.0"
fs2 = "0.4.3"
log = "0.4.14"
blake3 = "1.2.0"
fastrand = "1.6.0"

[dev-dependencies]
criterion = "0.3"
once_cell="1"
rayon="1"


[[bench]]
name = "my_benchmark"
harness = false
