[package]
name = "meshanina"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "2.1.0"
ethnum = "1.0.4"
zeroize = "1.4.3"
